spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/monitoring
    username: root
    password: shin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # 쿼리 출력
    properties:
      hibernate:
        format_sql: true # 쿼리를 보기 좋게 출력
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace # 쿼리 ? 값 출력
